name: "Iothereal"
version: "1.1.1"
slug: hassio_iothereal
description: >-
  Blazor UI in Home Assistant
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
url: "https://github.com/PeterRook/hassio-iothereal"
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - media:rw
  - share:rw
  - backup:rw

ingress: true
hassio_role : "manager"
codenotary: "rook0562@gmail.com"
apparmor: true
hassio_api : true
homeassistant_api: true
image: ghcr.io/peterrook/{arch}-hassiothereal
panel_icon: mdi:at
